name: Create Artifact

on:
  push:
    branches:
      - main  # Запускатиметься при пуші в гілку main
  workflow_dispatch: # Дозволяє запуск вручну

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Клонуйте ваш репозиторій
    - name: Checkout code
      uses: actions/checkout@v3

    # Створіть артефакт
    - name: Create Artifact
      run: zip -r html-css-artifact.zip . # Створення ZIP-файлу з усіма файлами

    # Збережіть артефакт
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: html-css-artifact
        path: html-css-artifact.zip
